name = "qr"
type = "webpack"

account_id = "fill-me"
workers_dev = true
compatibility_date = "2021-11-17"

[build.upload]
format = "service-worker"

[env.production]
route = "qr.example.com/*"
zone_id = "fill-me"
